### ISSUE TITLE
Twitch integration

### ISSUE THREAD

**Issue by Atomicbeast101** [Atomicbeast101/Jinux#3]
Jinux refuses to respond.

**Comment by Atomicbeast101** [comment]
Needs debugging.

**Comment by Atomicbeast101** [comment]
All commands work except for `-twitch add username`. If I try to add the an username that is already in the list, this error gets thrown in console:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "Jinux.py", line 168, in on_message
    active, Cmd_char)
  File "/home/adam/Jinux_Bot/cmds/twitch.py", line 14, in ex
    await c.send_message(c, '{}, `{}` is already in the list!'.format(m, u))
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1145, in send_message
    channel_id, guild_id = yield from self._resolve_destination(destination)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 289, in _resolve_destination
    raise InvalidArgument(fmt.format(destination))
discord.errors.InvalidArgument: Destination must be Channel, PrivateChannel, User, or Object. Received Client
```

**Comment by Atomicbeast101** [comment]
Welp. It was a simple human error. All good.
